apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeapp-customer-create-app
  labels:
    app: cafeapp-customer-create-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : cafeapp-customer-create-app
  template:
    metadata:
      labels:
        app: cafeapp-customer-create-app
    spec:
      containers:
      - name: cafeapp-customer-create-app
        image: karandua1992/cafeapp-customer-create:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name:  cafeapp-customer-create-svc
spec:
  selector:
    app:  cafeapp-customer-create-app
  ports:
  - port:  80
    targetPort:  8080