apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeapp-api-gateway-app
  labels:
    app: cafeapp-api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafeapp-api-gateway-app
  template:
    metadata:
      labels:
        app: cafeapp-api-gateway-app
    spec:
      containers:
        - name: cafeapp-api-gateway-app
          image: karandua1992/cafeapp-api-gateway:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: cafeapp-api-gateway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  selector:
    app: cafeapp-api-gateway-app