apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeapp-customer-updatetransaction-app
  labels:
    app: cafeapp-customer-updatetransaction-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : cafeapp-customer-updatetransaction-app
  template:
    metadata:
      labels:
        app: cafeapp-customer-updatetransaction-app
    spec:
      containers:
      - name: cafeapp-customer-updatetransaction-app
        image: karandua1992/cafeapp-customer-updatetransaction:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8087

---

kind: Service
apiVersion: v1
metadata:
  name:  cafeapp-customer-updatetransaction-svc
spec:
  selector:
    app:  cafeapp-customer-updatetransaction-app
  ports:
  - port:  80
    targetPort:  8087